import os
import shutil
import re
from pathlib import Path
import logging

def setup_logger():
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
    return logging.getLogger("Architect")

logger = setup_logger()

def create_config_paths(target_path, project_name):
    """Внедряет config_paths.py в целевой проект"""
    config_content = f'''import os
from pathlib import Path

# === AI-NATIVE PATH CONFIGURATION ===
# Auto-generated by AI-Native Toolkit

BASE_DIR = Path(__file__).resolve().parent
PROJECT_NAME = "{project_name}"
EXTERNAL_ROOT = BASE_DIR.parent

# 1. DATA (JSON, DB, CSV)
DATA_DIR = EXTERNAL_ROOT / "_data" / PROJECT_NAME
if not DATA_DIR.exists():
    DATA_DIR = BASE_DIR / "data"

# 2. LOGS
LOGS_DIR = EXTERNAL_ROOT / "_logs" / PROJECT_NAME
if not LOGS_DIR.exists():
    LOGS_DIR = BASE_DIR / "logs"

# 3. VENV (Reference only)
VENV_DIR = EXTERNAL_ROOT / "_venvs" / PROJECT_NAME

def get_path(filename, check_exists=False):
    """Smart path resolver: External > Internal"""
    external_path = DATA_DIR / filename
    local_path = BASE_DIR / filename
    
    if check_exists:
        if external_path.exists(): return external_path
        if local_path.exists(): return local_path
    
    return external_path
'''
    config_path = Path(target_path) / "config_paths.py"
    try:
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        logger.info(f"✅ [Bridge] Created {config_path.name}")
        return True
    except Exception as e:
        logger.error(f"❌ Failed to create config: {e}")
        return False

def restructure_project(target_path):
    """Главная функция архитектора"""
    target = Path(target_path).resolve()
    project_name = target.name
    parent_dir = target.parent

    # Новые локации
    new_dirs = {
        "venv": parent_dir / "_venvs" / project_name,
        "data": parent_dir / "_data" / project_name,
        "logs": parent_dir / "_logs" / project_name
    }

    print(f"\n🏗️  ARCHITECT: Restructuring {project_name}...")

    # 1. Создаем мост
    create_config_paths(target, project_name)

    # 2. Переносим файлы
    # Паттерны для переноса в _data
    data_patterns = ["*.json", "*.csv", "*.db", "*.sqlite", "*.sqlite3"]
    
    for folder_type, dest_path in new_dirs.items():
        dest_path.mkdir(parents=True, exist_ok=True)

    # === ПЕРЕНОС ТЯЖЕЛЫХ ПАПОК (Включая venv_gate) ===
    # Список папок, которые мы считаем "виртуальным окружением"
    venv_names = ["venv", ".venv", "venv_gate", "env"]
    
    for v_name in venv_names:
        old_venv = target / v_name
        if old_venv.exists() and old_venv.is_dir():
            print(f"📦 Found heavy folder: {v_name}")
            try:
                # Перемещаем. Если в _venvs уже есть папка, shutil.move кинет ошибку,
                # поэтому лучше сначала удалить старое там, если мы хотим перезаписать.
                if new_dirs["venv"].exists():
                    shutil.rmtree(new_dirs["venv"])
                
                print(f"📦 Moving {v_name} -> {new_dirs['venv']}...")
                shutil.move(str(old_venv), str(new_dirs["venv"]))
            except Exception as e:
                print(f"⚠️ Could not move {v_name}: {e}")

    # Перенос логов
    for log_file in target.glob("*.log"):
        try:
            shutil.move(str(log_file), str(new_dirs["logs"] / log_file.name))
        except Exception as e:
            print(f"⚠️ Could not move log {log_file.name}: {e}")
    
    if (target / "_PROJECT_LOG.md").exists():
        try:
            shutil.move(str(target / "_PROJECT_LOG.md"), str(new_dirs["logs"] / "_PROJECT_LOG.md"))
        except Exception as e:
            print(f"⚠️ Could not move _PROJECT_LOG.md: {e}")

    # Перенос данных (JSON, DB)
    for pattern in data_patterns:
        for f in target.glob(pattern):
            if f.name == "config_paths.py": continue # Не трогаем наш конфиг
            if "package" in str(f): continue # Не трогаем файлы внутри либ
            
            dest = new_dirs["data"] / f.name
            print(f"📦 Moving data {f.name} -> {dest}")
            try:
                shutil.move(str(f), str(dest))
            except Exception as e:
                print(f"⚠️ Could not move data {f.name}: {e}")

    # 3. Патчинг .bat файлов
    fix_launch_scripts(target, project_name)
    
    # 4. Чистка .cursorignore
    update_cursor_ignore(target)

    print(f"✨ Architecture updated! Dependencies are now external.")

def fix_launch_scripts(target_path, project_name):
    """Обновляет батники для запуска из внешнего venv"""
    # Используем сырую строку для пути к python
    # Важно: для regex замены мы должны экранировать бэкслеши
    
    # Путь который мы хотим видеть в батнике: ..\_venvs\Name\Scripts\python.exe
    rel_python_path = f'..\\_venvs\\{project_name}\\Scripts\\python.exe'
    
    # Формируем строку вызова. В bat файле это call "..."
    new_call_cmd = f'call "{rel_python_path}"'

    for bat in Path(target_path).glob("*.bat"):
        try:
            content = bat.read_text(encoding="utf-8", errors="ignore")
            
            # 1. Комментируем старую активацию venv
            # Ищем call ...activate
            content = re.sub(r'(?i)(call\s+.*?activate)', r'REM \1', content)

            # 2. Заменяем python main.py на полный путь
            # Ищем "python main.py" или "python bot.py"
            # Используем lambda, чтобы избежать проблем с backslash в строке замены
            content = re.sub(
                r'(?i)python\s+(.*?\.py)', 
                lambda m: f'{new_call_cmd} {m.group(1)}', 
                content
            )
            
            bat.write_text(content, encoding="utf-8")
            print(f"🔧 Patched launch script: {bat.name}")
        except Exception as e:
            print(f"⚠️ Failed to patch {bat.name}: {e}")

def update_cursor_ignore(target_path):
    """Обновляет игнор лист"""
    ignore_file = Path(target_path) / ".cursorignore"
    content = """# AI-Native Architecture
# Data and Env are external

_venvs/
_data/
_logs/
venv/
venv_gate/
.venv/
__pycache__/
*.pyc
"""
    try:
        ignore_file.write_text(content, encoding="utf-8")
        print("🧹 Updated .cursorignore")
    except Exception as e:
        print(f"⚠️ Failed to update .cursorignore: {e}")

# Точка входа для main.py
def run(args):
    restructure_project(args.path)
