import os
import shutil
import re
from pathlib import Path
import logging

def setup_logger():
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
    return logging.getLogger("Architect")

logger = setup_logger()

def create_config_paths(target_path, project_name):
    """Внедряет config_paths.py в целевой проект"""
    config_content = f'''import os
from pathlib import Path

# === AI-NATIVE PATH CONFIGURATION ===
# Auto-generated by AI-Native Toolkit

BASE_DIR = Path(__file__).resolve().parent
PROJECT_NAME = "{project_name}"
EXTERNAL_ROOT = BASE_DIR.parent

# 1. DATA (JSON, DB, CSV)
DATA_DIR = EXTERNAL_ROOT / "_data" / PROJECT_NAME
if not DATA_DIR.exists():
    DATA_DIR = BASE_DIR / "data"

# 2. LOGS
LOGS_DIR = EXTERNAL_ROOT / "_logs" / PROJECT_NAME
if not LOGS_DIR.exists():
    LOGS_DIR = BASE_DIR / "logs"

# 3. VENV (Reference only)
VENV_DIR = EXTERNAL_ROOT / "_venvs" / PROJECT_NAME

def get_path(filename, check_exists=False):
    """Smart path resolver: External > Internal"""
    external_path = DATA_DIR / filename
    local_path = BASE_DIR / filename
    
    if check_exists:
        if external_path.exists(): return external_path
        if local_path.exists(): return local_path
    
    return external_path
'''
    config_path = Path(target_path) / "config_paths.py"
    try:
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        logger.info(f"✅ [Bridge] Created {config_path.name}")
        return True
    except Exception as e:
        logger.error(f"❌ Failed to create config: {e}")
        return False

def restructure_project(target_path):
    """Главная функция архитектора"""
    target = Path(target_path).resolve()
    project_name = target.name
    parent_dir = target.parent

    # Новые локации
    new_dirs = {
        "venv": parent_dir / "_venvs" / project_name,
        "data": parent_dir / "_data" / project_name,
        "logs": parent_dir / "_logs" / project_name
    }

    print(f"\n🏗️  ARCHITECT: Restructuring {project_name}...")

    # 1. Создаем мост
    create_config_paths(target, project_name)

    # 2. Переносим файлы
    # Паттерны для переноса в _data
    data_patterns = ["*.json", "*.csv", "*.db", "*.sqlite", "*.sqlite3"]
    
    for folder_type, dest_path in new_dirs.items():
        dest_path.mkdir(parents=True, exist_ok=True)

    # Перенос VENV
    old_venv = target / "venv"
    if old_venv.exists():
        if new_dirs["venv"].exists():
            shutil.rmtree(new_dirs["venv"])
        print(f"📦 Moving venv -> {new_dirs['venv']}...")
        shutil.move(str(old_venv), str(new_dirs["venv"]))

    # Перенос логов
    for log_file in target.glob("*.log"):
        shutil.move(str(log_file), str(new_dirs["logs"] / log_file.name))
    
    if (target / "_PROJECT_LOG.md").exists():
        shutil.move(str(target / "_PROJECT_LOG.md"), str(new_dirs["logs"] / "_PROJECT_LOG.md"))

    # Перенос данных (JSON, DB)
    for pattern in data_patterns:
        for f in target.glob(pattern):
            if f.name == "config_paths.py": continue # Не трогаем наш конфиг
            if "package" in str(f): continue # Не трогаем файлы внутри либ
            
            dest = new_dirs["data"] / f.name
            print(f"📦 Moving data {f.name} -> {dest}")
            shutil.move(str(f), str(dest))
            
            # (Опционально) Оставляем симлинк или заглушку, если боимся сломать совсем всё?
            # Пока нет, мы полагаемся на config_paths.py

    # 3. Патчинг .bat файлов
    fix_launch_scripts(target, project_name)
    
    # 4. Чистка .cursorignore
    update_cursor_ignore(target)

    print(f"✨ Architecture updated! Dependencies are now external.")

def fix_launch_scripts(target_path, project_name):
    """Обновляет батники для запуска из внешнего venv"""
    new_python_path = f'call "..\\_venvs\\{project_name}\\Scripts\\python.exe"'
    
    for bat in target_path.glob("*.bat"):
        content = bat.read_text(encoding="utf-8", errors="ignore")
        # Простая замена вызова python
        if "venv\\Scripts\\activate" in content or "python main.py" in content:
            new_content = re.sub(r'call\s+venv\\Scripts\\activate', 'REM External Venv Used', content, flags=re.IGNORECASE)
            new_content = re.sub(r'python\s+main\.py', f'{new_python_path} main.py', new_content, flags=re.IGNORECASE)
            
            bat.write_text(new_content, encoding="utf-8")
            print(f"🔧 Patched launch script: {bat.name}")

def update_cursor_ignore(target_path):
    """Обновляет игнор лист"""
    ignore_file = target_path / ".cursorignore"
    content = """# AI-Native Architecture
# Data and Env are external

_venvs/
_data/
_logs/
__pycache__/
*.pyc
"""
    ignore_file.write_text(content, encoding="utf-8")
    print("🧹 Updated .cursorignore")

# Точка входа для main.py
def run(args):
    restructure_project(args.path)