"""
🧙 Interactive Wizard v3.2 — The Ultimate Doctor
Implements SDD, Active Cleaning, Hooks, and Rabbit Check
"""

from __future__ import annotations

import os
import re
import fnmatch
import subprocess
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass

# Try to import rich for beautiful TUI
try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm
    from rich.table import Table
    from rich.progress import Progress, SpinnerColumn, TextColumn
    from rich import box
    HAS_RICH = True
except ImportError:
    HAS_RICH = False

from ..core.constants import COLORS, VERSION, TEMPLATES
from ..core.config import set_default_ide, get_default_ai_targets
from ..core.file_utils import create_file
from .create import create_project
from .hooks import install_pre_commit_hook, check_hook_installed


# ═══════════════════════════════════════════════════════════════
# CONSTANTS
# ═══════════════════════════════════════════════════════════════

WIZARD_TEMPLATES = [
    ("bot", "🤖 Telegram Bot", "aiogram 3.x, handlers, keyboards"),
    ("webapp", "🌐 Web App", "Telegram Mini App (HTML/JS/CSS)"),
    ("fastapi", "⚡ FastAPI", "REST API with SQLAlchemy"),
    ("parser", "🕷️ Parser", "Web scraper with aiohttp"),
    ("empty", "📦 Empty", "Minimal structure, no modules"),
]

# Strict cursorignore template (includes _AI_ARCHIVE)
STRICT_CURSORIGNORE = '''# ═══════════════════════════════════════════════════════════════
# 🛑 CURSOR IGNORE — AI Toolkit Optimized
# Generated: {date}
# ═══════════════════════════════════════════════════════════════

# 1. VIRTUAL ENVIRONMENTS (Critical - saves ~500K tokens)
venv/**
.venv/**
env/**
**/site-packages/**

# 2. PYTHON RUNTIME
__pycache__/**
**/__pycache__/**
*.pyc
*.pyo
.pytest_cache/**
.mypy_cache/**
.ruff_cache/**

# 3. BUILD ARTIFACTS
dist/**
build/**
*.egg-info/**
*.whl
*.spec

# 4. SYSTEM / IDE
.git/**
.idea/**
.vscode/**
*.swp
*~
.DS_Store

# 5. DATA & LOGS
logs/**
*.log
data/**
*.csv
*.jsonl
*.sqlite
*.sqlite3
*.db

# 6. LOCK FILES
poetry.lock
Pipfile.lock
package-lock.json
yarn.lock

# 7. NODE MODULES
node_modules/**

# 8. SECRETS (Never index!)
.env
.env.*
!.env.example
*.pem
*.key

# 9. AI TOOLKIT ARCHIVE (Cleaned garbage)
_AI_ARCHIVE/**

# ═══════════════════════════════════════════════════════════════
# ⚠️ DO NOT IGNORE: README.md, src/**, docs/**, config files
# ═══════════════════════════════════════════════════════════════
'''


# ═══════════════════════════════════════════════════════════════
# VALIDATION
# ═══════════════════════════════════════════════════════════════

def validate_project_name(name: str) -> tuple[bool, str]:
    """Validate project name"""
    if not name:
        return False, "Name cannot be empty"
    if " " in name:
        return False, "Name cannot contain spaces"
    if not re.match(r'^[a-zA-Z][a-zA-Z0-9_-]*$', name):
        return False, "Name must start with letter, contain only letters/numbers/_/-"
    if len(name) > 50:
        return False, "Name too long (max 50 chars)"
    return True, ""


# ═══════════════════════════════════════════════════════════════
# SPEC.MD GENERATION (SDD)
# ═══════════════════════════════════════════════════════════════

def generate_spec_md(
    project_dir: Path,
    name: str,
    template: str,
    description: str
) -> None:
    """Generate spec.md for Spec-Driven Development"""
    
    template_info = dict(WIZARD_TEMPLATES).get(template, ("", "Unknown"))
    if isinstance(template_info, tuple):
        stack_info = template_info[1] if len(template_info) > 1 else ""
    else:
        stack_info = template_info
    
    content = f'''# 📋 Project Specification — {name}

> Generated by AI Toolkit v{VERSION} on {datetime.now().strftime("%Y-%m-%d %H:%M")}

## 🎯 Goal

{description if description else "TODO: Describe the main purpose of this project."}

## 🛠️ Tech Stack

- **Template:** {template}
- **Stack:** {stack_info}
- **Python:** 3.10+

## 🤖 AI Context Priming

1. **Read first:** `_AI_INCLUDE/PROJECT_CONVENTIONS.md`
2. **Understand:** This is a {template} project
3. **Remember:** venv is stored OUTSIDE in `../_venvs/{name}-venv/`

## 📝 TODO

- [ ] Configure `.env` with required secrets
- [ ] Implement core functionality
- [ ] Add tests
'''
    
    create_file(project_dir / "spec.md", content, quiet=True)


# ═══════════════════════════════════════════════════════════════
# RABBIT CHECK (Quick Code Review)
# ═══════════════════════════════════════════════════════════════

def run_rabbit_check(project_path: Path) -> tuple[bool, list[str]]:
    """
    Run quick code review check (The Rabbit)
    
    Args:
        project_path: Path to project
        
    Returns:
        Tuple of (passed, issues_list)
    """
    issues = []
    
    # Check 1: Russian text in Python files
    try:
        for py_file in project_path.rglob("*.py"):
            if "_AI_ARCHIVE" in str(py_file) or "venv" in str(py_file):
                continue
            try:
                content = py_file.read_text(encoding="utf-8", errors="ignore")
                # Check for Cyrillic characters
                if re.search(r'[а-яА-ЯёЁ]', content):
                    rel_path = py_file.relative_to(project_path)
                    issues.append(f"🇷🇺 Russian text in `{rel_path}`")
                    if len(issues) >= 5:
                        break
            except Exception:
                pass
    except Exception:
        pass
    
    # Check 2: venv inside project
    if (project_path / "venv").exists() or (project_path / ".venv").exists():
        issues.append("📁 venv directory found inside project")
    
    # Check 3: Missing .cursorignore
    if not (project_path / ".cursorignore").exists():
        issues.append("⚠️ Missing .cursorignore file")
    
    # Check 4: Missing _AI_INCLUDE
    if not (project_path / "_AI_INCLUDE").exists():
        issues.append("⚠️ Missing _AI_INCLUDE directory")
    
    # Check 5: Large Python files (>500 lines)
    try:
        for py_file in project_path.rglob("*.py"):
            if "_AI_ARCHIVE" in str(py_file) or "venv" in str(py_file):
                continue
            try:
                content = py_file.read_text(encoding="utf-8", errors="ignore")
                lines = len(content.splitlines())
                if lines > 500:
                    rel_path = py_file.relative_to(project_path)
                    issues.append(f"📏 Large file ({lines} lines): `{rel_path}`")
                    if len(issues) >= 5:
                        break
            except Exception:
                pass
    except Exception:
        pass
    
    return len(issues) == 0, issues[:5]


# ═══════════════════════════════════════════════════════════════
# GRAND FINAL REPORT
# ═══════════════════════════════════════════════════════════════

def generate_doctor_report(
    project_path: Path,
    before_files: int,
    before_tokens: int,
    after_files: int,
    after_tokens: int,
    archived_count: int,
    archived_size: int,
    rabbit_passed: bool,
    rabbit_issues: list[str],
    hook_installed: bool
) -> None:
    """Generate comprehensive DOCTOR_REPORT.md"""
    
    tokens_saved = before_tokens - after_tokens
    pct_saved = (tokens_saved / before_tokens * 100) if before_tokens > 0 else 0
    
    content = f'''# 🏥 Doctor Report — {project_path.name}

> Generated by AI Toolkit v{VERSION} on {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## 📊 Optimization Results

| Metric | Before | After | Improvement |
|--------|--------|-------|-------------|
| Files in Context | {before_files} | {after_files} | -{before_files - after_files} |
| Estimated Tokens | {before_tokens:,} | {after_tokens:,} | -{tokens_saved:,} ({pct_saved:.1f}%) |

## 🧹 Cleanup Results

- **Files Archived:** {archived_count}
- **Space Freed:** {archived_size / 1024:.1f} KB
- **Archive Location:** `_AI_ARCHIVE/`

## 🐇 Rabbit Check (Code Review)

**Status:** {"✅ PASSED" if rabbit_passed else "⚠️ ISSUES FOUND"}

'''
    
    if rabbit_issues:
        content += "**Issues:**\n"
        for issue in rabbit_issues:
            content += f"- {issue}\n"
    else:
        content += "No issues detected.\n"
    
    content += f'''
## 🔌 Git Hooks

**Pre-commit Hook:** {"✅ Installed" if hook_installed else "❌ Not installed"}

## 🎯 Recommendations

'''
    
    if not rabbit_passed:
        content += "1. Review and fix the issues listed above\n"
    if not hook_installed:
        content += "2. Consider installing the pre-commit hook: `ai-toolkit wizard` → Optimize\n"
    if pct_saved < 20:
        content += "3. Review `.cursorignore` to add more patterns\n"
    
    content += '''
---

*Report generated by AI Toolkit Doctor Mode.*
'''
    
    create_file(project_path / "DOCTOR_REPORT.md", content, quiet=True)


# ═══════════════════════════════════════════════════════════════
# FLOW A: CREATE NEW PROJECT (Rich)
# ═══════════════════════════════════════════════════════════════

def flow_create_rich(console: Console) -> bool:
    """Create new project flow with rich UI"""
    
    console.print(Panel(
        "[bold cyan]🐣 Create New Project[/bold cyan]\n"
        "[dim]Start fresh with an AI-optimized structure[/dim]",
        border_style="cyan"
    ))
    console.print()
    
    # Step 1: Project Name
    console.print("[bold]📝 Step 1/4: Project Name[/bold]")
    while True:
        name = Prompt.ask("  [cyan]Name[/cyan]", default="my_bot")
        is_valid, error = validate_project_name(name)
        if is_valid:
            console.print(f"  [green]✓[/green] {name}\n")
            break
        console.print(f"  [red]✗ {error}[/red]")
    
    # Step 2: Template
    console.print("[bold]📦 Step 2/4: Template[/bold]")
    table = Table(box=box.SIMPLE, show_header=False, padding=(0, 1))
    table.add_column("", width=3)
    table.add_column("", width=18)
    table.add_column("", style="dim")
    for i, (_, icon_name, desc) in enumerate(WIZARD_TEMPLATES, 1):
        table.add_row(f"[cyan]{i}[/cyan]", icon_name, desc)
    console.print(table)
    
    choice = Prompt.ask("  [cyan]Choice[/cyan]", choices=["1","2","3","4","5"], default="1")
    template_key, template_name, _ = WIZARD_TEMPLATES[int(choice) - 1]
    console.print(f"  [green]✓[/green] {template_name}\n")
    
    # Step 3: Description (SDD)
    console.print("[bold]📋 Step 3/4: Project Description[/bold]")
    console.print("  [dim]Brief description for AI context priming[/dim]")
    description = Prompt.ask("  [cyan]Description[/cyan]", default="")
    console.print()
    
    # Step 4: Options
    console.print("[bold]⚙️ Step 4/4: Options[/bold]")
    include_git = Confirm.ask("  [cyan]Git?[/cyan]", default=True)
    include_docker = Confirm.ask("  [cyan]Docker?[/cyan]", default=True)
    include_ci = Confirm.ask("  [cyan]CI/CD?[/cyan]", default=True)
    console.print()
    
    # Summary
    summary = Table(box=box.ROUNDED, show_header=False, border_style="green")
    summary.add_column("", style="cyan")
    summary.add_column("", style="bold")
    summary.add_row("📁 Project", name)
    summary.add_row("📦 Template", template_name)
    summary.add_row("📂 Location", str(Path.cwd() / name))
    
    console.print(Panel(summary, title="[bold]Summary[/bold]", border_style="green"))
    console.print()
    
    if not Confirm.ask("  [bold]Create project?[/bold]", default=True):
        console.print("  [yellow]Cancelled.[/yellow]\n")
        return False
    
    console.print()
    
    # Create project
    set_default_ide("all", ["cursor", "copilot", "claude", "windsurf"])
    
    with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"),
                  console=console, transient=True) as progress:
        progress.add_task("Creating project...", total=None)
        
        success = create_project(
            name=name, path=Path.cwd(),
            template=template_key if template_key != "empty" else "bot",
            ai_targets=get_default_ai_targets(),
            include_docker=include_docker, include_ci=include_ci, include_git=include_git,
        )
        
        if success and description:
            generate_spec_md(Path.cwd() / name, name, template_key, description)
    
    if success:
        console.print(Panel(
            f"[bold green]🎉 Project created![/bold green]\n\n"
            f"  [cyan]cd {name}[/cyan]\n"
            f"  [cyan]./scripts/bootstrap.sh[/cyan]",
            border_style="green"
        ))
    
    return success


# ═══════════════════════════════════════════════════════════════
# FLOW B: THE ULTIMATE DOCTOR (Rich)
# ═══════════════════════════════════════════════════════════════

def flow_optimize_rich(console: Console) -> bool:
    """The Ultimate Doctor flow with rich UI"""
    from ..utils.metrics import scan_project, ScanResult
    from ..utils.cleaner import archive_artifacts
    
    console.print(Panel(
        "[bold magenta]🏥 The Ultimate Doctor[/bold magenta]\n"
        "[dim]Deep optimization: Clean → Protect → Verify[/dim]",
        border_style="magenta"
    ))
    console.print()
    
    # ─────────────────────────────────────────────────────────────
    # Project Path Selection
    # ─────────────────────────────────────────────────────────────
    console.print("[bold]📂 Select Project[/bold]")
    path_str = Prompt.ask("  [cyan]Path[/cyan]", default=".")
    project_path = Path(path_str).resolve()
    
    if not project_path.exists() or not project_path.is_dir():
        console.print(f"  [red]✗ Invalid path[/red]\n")
        return False
    
    console.print(f"  [green]✓[/green] {project_path}\n")
    
    # ─────────────────────────────────────────────────────────────
    # Step 1: 📸 Snapshot Before
    # ─────────────────────────────────────────────────────────────
    console.print(Panel("[bold]📸 Step 1/6: Initial Snapshot[/bold]", border_style="blue"))
    
    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        p.add_task("Scanning project...")
        before = scan_project(project_path)
    
    console.print(f"  📁 Files: [bold]{before.files_count}[/bold]")
    console.print(f"  🎯 Tokens: [bold]{before.formatted_tokens}[/bold]\n")
    
    # ─────────────────────────────────────────────────────────────
    # Step 2: 🧹 Active Cleaning
    # ─────────────────────────────────────────────────────────────
    console.print(Panel("[bold]🧹 Step 2/6: Active Cleaning[/bold]", border_style="blue"))
    
    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        p.add_task("Archiving garbage files...")
        archive_result = archive_artifacts(project_path)
    
    if archive_result.count_moved > 0:
        console.print(f"  📦 Archived: [bold]{archive_result.count_moved}[/bold] items")
        console.print(f"  💾 Freed: [bold]{archive_result.formatted_size}[/bold]")
        console.print(f"  📂 Location: [cyan]_AI_ARCHIVE/[/cyan]\n")
    else:
        console.print("  [dim]No garbage files found[/dim]\n")
    
    # ─────────────────────────────────────────────────────────────
    # Step 3: 🛡️ Passive Protection
    # ─────────────────────────────────────────────────────────────
    console.print(Panel("[bold]🛡️ Step 3/6: Passive Protection[/bold]", border_style="blue"))
    
    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        task = p.add_task("Creating protection rules...")
        
        # Create .cursorignore
        cursorignore_content = STRICT_CURSORIGNORE.format(date=datetime.now().strftime("%Y-%m-%d"))
        create_file(project_path / ".cursorignore", cursorignore_content, quiet=True)
        
        # Create .cursor/rules/
        cursor_rules_dir = project_path / ".cursor" / "rules"
        cursor_rules_dir.mkdir(parents=True, exist_ok=True)
        
        project_md = f'''# 📋 {project_path.name}

Optimized by AI Toolkit Doctor on {datetime.now().strftime("%Y-%m-%d")}.

## Conventions
- Python 3.10+ with type hints
- English only (no Russian)
- PEP 8 formatting
'''
        create_file(cursor_rules_dir / "project.md", project_md, quiet=True)
    
    console.print("  [green]✓[/green] Created .cursorignore")
    console.print("  [green]✓[/green] Created .cursor/rules/\n")
    
    # ─────────────────────────────────────────────────────────────
    # Step 4: 📸 Snapshot After
    # ─────────────────────────────────────────────────────────────
    console.print(Panel("[bold]📸 Step 4/6: Final Snapshot[/bold]", border_style="blue"))
    
    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        p.add_task("Re-scanning project...")
        after = scan_project(project_path)
    
    console.print(f"  📁 Files: [bold]{after.files_count}[/bold]")
    console.print(f"  🎯 Tokens: [bold]{after.formatted_tokens}[/bold]\n")
    
    # ─────────────────────────────────────────────────────────────
    # Step 5: 🐇 The Rabbit Check
    # ─────────────────────────────────────────────────────────────
    console.print(Panel("[bold]🐇 Step 5/6: Rabbit Check (Code Review)[/bold]", border_style="blue"))
    
    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        p.add_task("Running code checks...")
        rabbit_passed, rabbit_issues = run_rabbit_check(project_path)
    
    if rabbit_passed:
        console.print("  [green]✅ All checks passed![/green]\n")
    else:
        console.print(f"  [yellow]⚠️ Found {len(rabbit_issues)} issue(s):[/yellow]")
        for issue in rabbit_issues:
            console.print(f"    • {issue}")
        console.print()
    
    # ─────────────────────────────────────────────────────────────
    # Step 6: 🔌 Git Hooks
    # ─────────────────────────────────────────────────────────────
    console.print(Panel("[bold]🔌 Step 6/6: Git Hooks[/bold]", border_style="blue"))
    
    hook_installed = False
    git_exists = (project_path / ".git").exists()
    
    if git_exists:
        already_installed = check_hook_installed(project_path)
        if already_installed:
            console.print("  [green]✓[/green] Pre-commit hook already installed\n")
            hook_installed = True
        else:
            if Confirm.ask("  [cyan]Install pre-commit hook?[/cyan]", default=True):
                hook_installed = install_pre_commit_hook(project_path)
                if hook_installed:
                    console.print("  [green]✓[/green] Hook installed\n")
                else:
                    console.print("  [red]✗[/red] Failed to install hook\n")
            else:
                console.print("  [dim]Skipped[/dim]\n")
    else:
        console.print("  [dim]No .git directory found (skipped)[/dim]\n")
    
    # ─────────────────────────────────────────────────────────────
    # 📊 Grand Final Report
    # ─────────────────────────────────────────────────────────────
    tokens_saved = before.token_est - after.token_est
    pct_saved = (tokens_saved / before.token_est * 100) if before.token_est > 0 else 0
    
    # Table 1: Optimization
    opt_table = Table(title="📊 Optimization Results", box=box.ROUNDED, border_style="green")
    opt_table.add_column("Metric", style="cyan")
    opt_table.add_column("Before", justify="right", style="red")
    opt_table.add_column("After", justify="right", style="green")
    opt_table.add_column("Saved", justify="right", style="yellow")
    
    opt_table.add_row("📁 Files", str(before.files_count), str(after.files_count),
                      f"-{before.files_count - after.files_count}")
    opt_table.add_row("🎯 Tokens", before.formatted_tokens, after.formatted_tokens,
                      f"-{tokens_saved // 1000}K ({pct_saved:.1f}%)")
    opt_table.add_row("🧹 Archived", "-", "-", f"{archive_result.count_moved} items")
    
    # Table 2: Health
    health_table = Table(title="🏥 Health Status", box=box.ROUNDED, border_style="cyan")
    health_table.add_column("Check", style="cyan")
    health_table.add_column("Status", justify="center")
    
    health_table.add_row("🐇 Rabbit Check", "[green]✅ PASS[/green]" if rabbit_passed else "[yellow]⚠️ ISSUES[/yellow]")
    health_table.add_row("🔌 Git Hook", "[green]✅ Installed[/green]" if hook_installed else "[dim]Not installed[/dim]")
    health_table.add_row("🛡️ .cursorignore", "[green]✅ Created[/green]")
    
    console.print()
    console.print(Panel(opt_table, border_style="green"))
    console.print()
    console.print(Panel(health_table, border_style="cyan"))
    console.print()
    
    # Generate report file
    generate_doctor_report(
        project_path, before.files_count, before.token_est,
        after.files_count, after.token_est,
        archive_result.count_moved, archive_result.size_freed,
        rabbit_passed, rabbit_issues, hook_installed
    )
    
    console.print(f"  📄 Full report: [cyan]DOCTOR_REPORT.md[/cyan]\n")
    
    return True


# ═══════════════════════════════════════════════════════════════
# PLAIN TEXT FALLBACKS
# ═══════════════════════════════════════════════════════════════

def flow_create_plain() -> bool:
    """Create flow with plain text"""
    print(f"{COLORS.colorize('🐣 Create New Project', COLORS.CYAN)}\n")
    
    while True:
        name = input("  Project name [my_bot]: ").strip() or "my_bot"
        is_valid, error = validate_project_name(name)
        if is_valid:
            break
        print(f"  {COLORS.error(f'✗ {error}')}")
    
    print("  Template:")
    for i, (_, icon_name, desc) in enumerate(WIZARD_TEMPLATES, 1):
        print(f"    {i}. {icon_name}")
    choice = input("  Choice [1]: ").strip() or "1"
    try:
        template_key, _, _ = WIZARD_TEMPLATES[int(choice) - 1]
    except:
        template_key = "bot"
    
    description = input("  Description: ").strip()
    include_git = input("  Git? (Y/n): ").strip().lower() != 'n'
    include_docker = input("  Docker? (Y/n): ").strip().lower() != 'n'
    include_ci = input("  CI/CD? (Y/n): ").strip().lower() != 'n'
    
    if input("  Create? (Y/n): ").strip().lower() == 'n':
        return False
    
    set_default_ide("all", ["cursor", "copilot", "claude", "windsurf"])
    success = create_project(
        name=name, path=Path.cwd(),
        template=template_key if template_key != "empty" else "bot",
        ai_targets=get_default_ai_targets(),
        include_docker=include_docker, include_ci=include_ci, include_git=include_git,
    )
    
    if success and description:
        generate_spec_md(Path.cwd() / name, name, template_key, description)
    
    return success


def flow_optimize_plain() -> bool:
    """Optimize flow with plain text"""
    from ..utils.metrics import scan_project
    from ..utils.cleaner import archive_artifacts
    
    print(f"{COLORS.colorize('🏥 The Ultimate Doctor', COLORS.MAGENTA)}\n")
    
    path_str = input("  Project path [.]: ").strip() or "."
    project_path = Path(path_str).resolve()
    
    if not project_path.exists():
        print(f"  {COLORS.error('Invalid path')}")
        return False
    
    print("\n  Step 1: Scanning...")
    before = scan_project(project_path)
    print(f"  Files: {before.files_count}, Tokens: {before.formatted_tokens}")
    
    print("\n  Step 2: Cleaning...")
    archive_result = archive_artifacts(project_path)
    print(f"  Archived: {archive_result.count_moved} items")
    
    print("\n  Step 3: Creating protection...")
    cursorignore_content = STRICT_CURSORIGNORE.format(date=datetime.now().strftime("%Y-%m-%d"))
    create_file(project_path / ".cursorignore", cursorignore_content, quiet=True)
    
    print("\n  Step 4: Re-scanning...")
    after = scan_project(project_path)
    print(f"  Files: {after.files_count}, Tokens: {after.formatted_tokens}")
    
    print("\n  Step 5: Rabbit check...")
    rabbit_passed, rabbit_issues = run_rabbit_check(project_path)
    print(f"  Status: {'PASS' if rabbit_passed else 'ISSUES FOUND'}")
    
    hook_installed = False
    if (project_path / ".git").exists():
        if input("\n  Install git hook? (Y/n): ").strip().lower() != 'n':
            hook_installed = install_pre_commit_hook(project_path)
    
    tokens_saved = before.token_est - after.token_est
    pct_saved = (tokens_saved / before.token_est * 100) if before.token_est > 0 else 0
    
    print(f"\n{COLORS.colorize('═' * 40, COLORS.GREEN)}")
    print(f"  Tokens: {before.formatted_tokens} → {after.formatted_tokens} (-{pct_saved:.1f}%)")
    print(f"  Rabbit: {'✅ PASS' if rabbit_passed else '⚠️ ISSUES'}")
    print(f"{COLORS.colorize('═' * 40, COLORS.GREEN)}\n")
    
    generate_doctor_report(
        project_path, before.files_count, before.token_est,
        after.files_count, after.token_est,
        archive_result.count_moved, archive_result.size_freed,
        rabbit_passed, rabbit_issues, hook_installed
    )
    
    return True


# ═══════════════════════════════════════════════════════════════
# MAIN WIZARD ENTRY POINT
# ═══════════════════════════════════════════════════════════════

def run_wizard_rich() -> bool:
    """Run wizard with rich UI"""
    console = Console()
    
    console.print()
    console.print(Panel.fit(
        f"[bold cyan]🧙 AI Toolkit Wizard v{VERSION}[/bold cyan]\n"
        "[dim]Create & Optimize AI-friendly projects[/dim]",
        border_style="cyan", box=box.DOUBLE
    ))
    console.print()
    
    console.print("[bold]What would you like to do?[/bold]\n")
    console.print("  [cyan]1.[/cyan] 🐣 [bold]Create New Project[/bold]")
    console.print("  [cyan]2.[/cyan] 🏥 [bold]The Ultimate Doctor[/bold] (Optimize)")
    console.print()
    
    choice = Prompt.ask("  [cyan]Choice[/cyan]", choices=["1", "2"], default="1")
    console.print()
    
    if choice == "1":
        return flow_create_rich(console)
    else:
        return flow_optimize_rich(console)


def run_wizard_plain() -> bool:
    """Run wizard with plain text"""
    print(f"\n{COLORS.colorize('🧙 AI Toolkit Wizard', COLORS.CYAN)}\n")
    print("  1. 🐣 Create New Project")
    print("  2. 🏥 The Ultimate Doctor (Optimize)")
    
    choice = input("\n  Choice [1]: ").strip() or "1"
    
    if choice == "1":
        return flow_create_plain()
    elif choice == "2":
        return flow_optimize_plain()
    return False


def run_wizard() -> bool:
    """Run the interactive wizard"""
    if HAS_RICH:
        return run_wizard_rich()
    else:
        return run_wizard_plain()


def cmd_wizard() -> None:
    """Interactive wizard command wrapper"""
    run_wizard()
